# services/exceptions.py

class ValidationError(Exception):
    """Кастомне виключення для валідації введення користувача."""
    pass
